Are you suffering from headaches for a long time? ğŸ§ ğŸ¤•

If yes, then it is time to consult a neurosurgeon and get rid of headaches! ğŸ˜ŒğŸ‘

Common symptoms of headaches include:

- Tension-based headaches ğŸ§˜â€â™€
- Recurrent headaches ğŸ”
- Migraine headache types ğŸ¤¯
- Headaches caused by brain tumors ğŸ§ ğŸ’¡
- Cluster headaches ğŸŒ
- Cervical headaches ğŸ’¼

Contact us and get your problem solved!
Dr. Shivam Gaur, MBBS MS (Surgery) Hamidia, Bhopal, Mch Neurosurgery, IPGMER, Kolkata ğŸ¥

Contact for appointment ğŸ“:

ğŸ“± 7047669641, 7000206208

ğŸ“ Neuro Care Clinic: Shop No. 3, Sukhbir Complex, Opposite Manubhavan Tekri, Lalghati, Bhopal (M.P.)
